# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - 
    id: "h3sh"
    main: ./cmd/h3sh/main.go
    binary: h3sh
    goos:
      - linux
    goarch: 
      - arm64
    tags:
      - osusergo
      - netgo
      - static_build
      - feature
  - 
    id: "h3sh-server"
    main: ./cmd/h3sh-server/main.go
    binary: h3sh-server
    env:
      - CC=/tmp/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
      - CGO_ENABLED=1
      - CGO_CFLAGS=
    ldflags:
      - -extld=/tmp/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
      - -extldflags=-static
      - -linkmode=external
    goos:
      - linux
    goarch:
      - arm64
    hooks:
      pre:
        - sudo cp /usr/bin/{{ .Arch }}-ld /usr/bin/ld
    tags:
      - osusergo
      - netgo
      - static_build
      - feature

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_linux_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_linux_arm64_checksums.txt'


release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto